### ISSUE TITLE
[BUG] `generation` and `observedGeneration`  of CloneSet in karmada is not aligned.

### ISSUE THREAD

**Issue by veophi** [karmada-io/karmada#4866] opened 2024-04-24 09:44 UTC
**What happened**:
`status.bservedGeneration` of **federated resource** (CloneSet)  **does not align** with its `metadata.generation`.

**What's the meaning of `status.bservedGeneration`?**
<img width="1248" alt="image" src="https://github.com/karmada-io/karmada/assets/28217554/8bbbf8c5-46e4-4371-b924-95abd85c61e9">
However, Karmada uses `status.bservedGeneration` of **member resource** as its `status.bservedGeneration` in **federated resource**, it's incorrect.

**What you expected to happen**:
`status.bservedGeneration` of **federated resource** (CloneSet) **aligns** with its `metadata.generation` if its all member resources have `status.observedGeneration >= metadata.generation`.

**How to reproduce it (as minimally and precisely as possible)**:
Update any federated Deployment spec and watch its generation&observedGeneration.

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by XiShanYongYe-Chang** [comment] 2024-04-24 10:09
I've tested it and it doesn't seem to reproduce the problem.

![image](https://github.com/karmada-io/karmada/assets/78244870/0e91cce1-9049-40ff-aed0-bae0b37303b0)

**Comment by veophi** [comment] 2024-04-24 11:46
> reproduce

@XiShanYongYe-Chang  

Sorry, Deployment generation is another bug.
But, this bug is easily reproduced with `CloneSet` when the `generation` in member is inconsistent with in karmada.

```shell
➜  ~ use_karmada
➜  ~ k get clone -oyaml | grep -i generation
    generation: 2
    observedGeneration: 4
    generation: 5
    observedGeneration: 4
➜  ~
```

**Comment by XiShanYongYe-Chang** [comment] 2024-04-24 11:54
> Sorry, Deployment generation is another bug.

If there is another bug, we can track it with a new issue.

> But, this bug is easily reproduced with CloneSet when the generation in member is inconsistent with in karmada.

I got it. This is because we did not implement a state collection resource interpreter for the cloneset resource.

https://github.com/karmada-io/karmada/blob/6e5a6029922091e22bdae470323c2483334273ff/pkg/resourceinterpreter/interpreter.go#L62

https://github.com/karmada-io/karmada/blob/6e5a6029922091e22bdae470323c2483334273ff/pkg/resourceinterpreter/interpreter.go#L56

**Comment by veophi** [comment] 2024-04-24 11:56
> > Sorry, Deployment generation is another bug.
> 
> If there is another bug, we can track it with a new issue.
> 
> > But, this bug is easily reproduced with CloneSet when the generation in member is inconsistent with in karmada.
> 
> I got it. This is because we did not implement a state collection resource interpreter for the cloneset resource.
> 
> https://github.com/karmada-io/karmada/blob/6e5a6029922091e22bdae470323c2483334273ff/pkg/resourceinterpreter/interpreter.go#L62
> 
> https://github.com/karmada-io/karmada/blob/6e5a6029922091e22bdae470323c2483334273ff/pkg/resourceinterpreter/interpreter.go#L56


@XiShanYongYe-Chang  here's bug  https://github.com/karmada-io/karmada/blob/6e5a6029922091e22bdae470323c2483334273ff/pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CloneSet/customizations.yaml#L72

**Comment by XiShanYongYe-Chang** [comment] 2024-04-24 12:01
Oh... Here it is, sorry I forgot. 

Let me invite the owner of the feature to take a look at this issue. 
Hi @yike21, can you help take a look?
/cc @yike21 

By the way, do you know how to fix it?

**Comment by veophi** [comment] 2024-04-24 12:27
> Oh... Here it is, sorry I forgot.
> 
> Let me invite the owner of the feature to take a look at this issue. Hi @yike21, can you help take a look? /cc @yike21
> 
> By the way, do you know how to fix it?

@XiShanYongYe-Chang  yes, I know. 

Deployment Generation bug and its fix is here: https://github.com/karmada-io/karmada/pull/4867

**Comment by XiShanYongYe-Chang** [comment] 2024-04-24 12:33
> BTW, Deployment generation bug and its fix is here: #4867

Thanks a lot~

**Comment by yike21** [comment] 2024-04-24 13:04
> Let me invite the owner of the feature to take a look at this issue. Hi @yike21, can you help take a look? /cc @yike21
> 
> By the way, do you know how to fix it?

I will do it asap. Thanks a lot! @veophi

**Comment by veophi** [comment] 2024-04-25 02:47
//TODO: CloneSet generation logic will be fixed later. @XiShanYongYe-Chang  @yike21

**Comment by XiShanYongYe-Chang** [comment] 2024-04-25 03:59
Hi @veophi I've had a look at PR #4867, but I don't understand what the problem was with the previous Deployment status observedGeneration. I understand that the previous logic was to set observedGeneration directly to deployment generation when the status was aggregated, as described in the [comments](https://github.com/karmada-io/karmada/blob/006aff95187c33886b7b32348fdf8dce8d9f8650/pkg/resourceinterpreter/default/native/aggregatestatus.go#L79-L82). The current behavior may be more rigorous. The waits for the Deployment state in the member cluster to be ready before proceeding with the collection.

**Comment by veophi** [comment] 2024-04-25 05:08
> Hi @veophi I've had a look at PR #4867, but I don't understand what the problem was with the previous Deployment status observedGeneration. I understand that the previous logic was to set observedGeneration directly to deployment generation when the status was aggregated, as described in the [comments](https://github.com/karmada-io/karmada/blob/006aff95187c33886b7b32348fdf8dce8d9f8650/pkg/resourceinterpreter/default/native/aggregatestatus.go#L79-L82). The current behavior may be more rigorous. The waits for the Deployment state in the member cluster to be ready before proceeding with the collection.

Do you have wechat?

**Comment by veophi** [comment] 2024-04-25 05:29
@XiShanYongYe-Chang  `observedGeneration == generation` means the Deployment controller has observed the spec(generation) changes and updated the status based on the changes.

If you always set `observedGeneration = deploy.Generation` and ignore whether the `status`  corresponds to the `generation`,  the status you aggregated will be untrustworthy.

**Comment by XiShanYongYe-Chang** [comment] 2024-04-25 08:43
Thanks~ @yike21 

Can you help create an umbrella issue to track the task? Each resource to be processed can be processed as a subtask.

**Comment by yike21** [comment] 2024-04-25 08:44
> Can you help create an umbrella issue to track the task? Each resource to be processed can be processed as a subtask.

OK, I will do it soon.

**Comment by XiShanYongYe-Chang** [comment] 2024-04-25 13:12
As an evolution of the previous resource template status.observedGeneration solution, I think that we can continue to promote the current issue as a feature.

We can use #4870 to trace subsequent tasks. Thanks again @veophi @yike21 

/kind feature

**Comment by XiShanYongYe-Chang** [comment] 2024-06-14 08:57
We will use issue #4870 to track the task list.
Let us close it first.
/close

**Closed by XiShanYongYe-Chang** 2024-06-14 08:57 UTC
Labels: kind/bug, kind/feature
