### ISSUE TITLE
Failed to create or update resource longer than 63 chars

### ISSUE THREAD

**Issue by a7i** [karmada-io/karmada#4683] opened 2024-03-05 23:52 UTC
**What happened**:

we have a role called `kube-system/compute-controller-manager-leader-election-rolebinding`, given that karmada adds it in the label, it cannot be longer than 63 characters
```
4m55s       Warning   SyncFailed               rolebinding/compute-controller-manager-leader-election-rolebinding   Failed to create or update resource(kube-system/compute-controller-manager-leader-election-rolebinding) in member cluster(eks-sandbox): RoleBinding.rbac.authorization.k8s.io "compute-controller-manager-leader-election-rolebinding" is invalid: metadata.labels: Invalid value: "compute-controller-manager-leader-election-rolebinding-9d54c6969": must be no more than 63 characters
```

**What you expected to happen**:
I would have expected to only use annotations, but not sure what should happent to the label

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a role or rolebinding called `compute-controller-manager-leader-election-rolebinding`
2. Create a PropagationPolicy for it
3. Observe event failures / no resourcebinding getting created

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.9.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by XiShanYongYe-Chang** [comment] 2024-03-06 03:11
Hi @a7i, the issue you mentioned is being resolved in https://github.com/karmada-io/karmada/issues/4000. Can you help confirm it?

**Comment by a7i** [comment] 2024-03-06 20:32
Hi @XiShanYongYe-Chang that's exactly it. Anything we can help with? Happy to contribute

**Comment by XiShanYongYe-Chang** [comment] 2024-03-08 01:50
> Hi @XiShanYongYe-Chang that's exactly it. Anything we can help with? Happy to contribute

I'll sort out how far this task has gone recently, and I'll give you a reply after I've sorted it out.

**Comment by grosser** [comment] 2024-03-13 21:14
@XiShanYongYe-Chang any progress ... anything that we can help with ?

**Comment by XiShanYongYe-Chang** [comment] 2024-03-14 01:12
> @XiShanYongYe-Chang any progress ... anything that we can help with ?

Hi @grosser, being analyzed 🔥 (Code walk-through shows that many changes are involved.) Later, I will list the current progress and to-do items and provide the analysis result as soon as possible.

**Comment by XiShanYongYe-Chang** [comment] 2024-03-14 08:51
Hi @a7i @grosser, I've got a list of things to do in #4711, would you like to get involved?

**Comment by grosser** [comment] 2024-03-14 19:06
awesome list, thx!
I added helping out to our backlog (ticket 888 hehe) so we'll hopefully get this moving next week+

**Comment by RainbowMango** [comment] 2024-03-28 03:16
I guess we can have a quick fix for this.

The root cause is the length of the resource template name (`compute-controller-manager-leader-election-rolebinding-9d54c6969`) exceeds 63 chars, and the `Work` name is built with this name(`resourcename-<hash value>`), and the `Work` name eventually added to the workload at https://github.com/karmada-io/karmada/blob/ff7322acf252632ef2c20864b904a6cd65fa5400/pkg/controllers/binding/common.go#L158-L159.

The labels added to the workload are used for observability, we already added similar value to the annotation, so we can remove the redundant labels now.

**Comment by RainbowMango** [comment] 2024-03-28 03:25
/assign @XiShanYongYe-Chang 
In favor of #4765

**Closed** 2024-03-28 06:08 UTC
Labels: kind/bug
