### ISSUE TITLE
Should a label mismatch in PropagationPolicy placement delete resources from member clusters?

### ISSUE THREAD

**Issue by cebernardi** [karmada-io/karmada#2906] opened 2022-12-06 12:37 UTC
**Please provide an in-depth description of the question you have**:
If a PropagationPolicy targets a set of member clusters by labels:

```
  placement:
    clusterAffinity:
      labelSelector:
        matchLabels:
          phase: setup
```

and a the label value is changed on the cluster resource:

```
kubectl --context=karmada-api-server label cluster my-cluster phase=ready
```
the resources targeted by the `PropagationPolicy` are not removed from the member cluster `my-cluster`.

Is this the expected behavior or am I missing something?

**What do you think about this question?**:
I was expecting that Karmada would reconcile the placement and remove the resource from the member cluster that doesn't match the placement anymore.

I'm aware of [this](https://karmada.io/docs/userguide/scheduling/resource-propagating#delete-a-propagationpolicy), but it feels to me that labels placement mismatch is a different scenario.

**Environment**:
- Karmada version: 1.4.0
- Kubernetes version: 1.24
- Others:

**Comment by XiShanYongYe-Chang** [comment] 2022-12-07 02:38
@cebernardi Thank you for your discovery. This is a stable reproduction of the problem. The reason is that label deletion is not considered when the cluster update event is processed:

https://github.com/karmada-io/karmada/blob/e6ba531a739668af1459e4f7d4c2a5cd80fb163e/pkg/scheduler/event_handler.go#L228-L234

We will fix it as soon as possible.

/kind bug

**Comment by RainbowMango** [comment] 2022-12-07 03:43
/priority important-soon
@cebernardi Thanks for spotting and sorry for the inconvenience. 

This issue will be fixed on the master branch, and a cherry-pick will be applied to release-1.4 after that. So, the patch will be available in v1.4.1.

**Closed** 2022-12-13 09:06 UTC
Labels: kind/bug, kind/question, priority/important-soon

**Comment by RainbowMango** [comment] 2022-12-13 09:53
@cebernardi 
Just a notice, we just fixed this issue on the master branch, and we are going to tag a new patch release for release-1.4 this week. So, this patch should be available in v1.4.1.

**Comment by cebernardi** [comment] 2022-12-20 21:05
Thank you, trying it asap!

**Comment by cebernardi** [comment] 2023-01-06 17:44
thanks, works like a charm!

**Comment by RainbowMango** [comment] 2025-08-02 09:45
Hi @cebernardi, It's been a while since the last time I heard from you. Hope you are doing well :)
Just wanted to check in: Are you using Karmada now? If so, have you run into any further issues or any feedback for us?

PS: I'm currently looking into another related issue and traced it back to this thread.
