### ISSUE TITLE
install karmada by helm error

### ISSUE THREAD

**Issue by chestarss** [karmada-io/karmada#1374] opened 2022-02-18 03:41 UTC
**What happened**:
```
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /Users/chestar/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /Users/chestar/.kube/config
I0218 11:38:29.692979   92599 request.go:668] Waited for 1.057336792s due to client-side throttling, not priority and fairness, request: GET:https://*****:6443/apis/clusterregistry.k8s.io/v1alpha1?timeout=32s
I0218 11:38:39.693284   92599 request.go:668] Waited for 11.057638334s due to client-side throttling, not priority and fairness, request: GET:https://*****:6443/apis/networkaddonsoperator.network.kubevirt.io/v1alpha1?timeout=32s
Error: chart requires kubeVersion: >=1.16.0 which is incompatible with Kubernetes v1.22.0-rc.0+a44d0f0

```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.0.1
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

```
kubectl version                                                                                                                                                            git:(v1.0.1|)
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.0-rc.0+a44d0f0", GitCommit:"a44d0f017717d7bdd02c6fb64957e1380b821496", GitTreeState:"clean", BuildDate:"2021-10-22T03:07:44Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by pigletfly** [comment] 2022-02-18 03:49
duplicate of https://github.com/karmada-io/karmada/issues/1339

**Comment by RainbowMango** [comment] 2022-02-18 06:24
Thanks @chestarss . Let's track this issue by #1339.

/close

**Closed by RainbowMango** 2022-02-18 06:24 UTC
Labels: kind/bug
