### ISSUE TITLE
 ReplicaSchedulingPolicy's resourceSelector without namespace should inherit namespace from ObjectMeta.Namespace

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#433] opened 2021-06-10 08:55 UTC
**What would you like to be added**:

When a ReplicaSchedulingPolicy's resourceSelector without specifying a namespace, it should inherit namespace from ObjectMeta.Namespace, just like PropagationPolicy.

**Comment by RainbowMango** [comment] 2021-06-11 08:34
Did I miss something? I think the behavior already works as expected.
Share your reproduce steps?

**Comment by XiShanYongYe-Chang** [comment] 2021-06-11 09:17
Sorry, I make a mistake, it's not PropagationPolicy, it's ReplicaSchedulingPolicy.

When I create a ReplicaSchedulingPolicy with yaml:

```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: ReplicaSchedulingPolicy
metadata:
  name: foo
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  totalReplicas: 30
  preferences:
    staticWeightList:
      - targetCluster:
          clusterNames: [member1]
        weight: 1
      - targetCluster:
          clusterNames: [member2]
        weight: 2
```
It's resourceSelectors have empty namespace:
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: ReplicaSchedulingPolicy
metadata:
  creationTimestamp: "2021-06-11T09:06:53Z"
  generation: 1
  name: foo
  namespace: default
  resourceVersion: "397153"
  selfLink: /apis/policy.karmada.io/v1alpha1/namespaces/default/replicaschedulingpolicies/foo
  uid: 27d59499-c5dd-4f0f-8d5b-0fa9e10dcf34
spec:
  preferences:
    staticWeightList:
    - targetCluster:
        clusterNames:
        - member1
      weight: 1
    - targetCluster:
        clusterNames:
        - member2
      weight: 2
  resourceSelectors:  
  - apiVersion: apps/v1 # namespace is empty
    kind: Deployment
    name: nginx
  totalReplicas: 30
```

I think that's part of the reason for #402 .

**Comment by RainbowMango** [comment] 2021-06-11 09:25
Yes, the issue is fixed by https://github.com/karmada-io/karmada/pull/410.

Have you found any other problems after this patch?

**Comment by XiShanYongYe-Chang** [comment] 2021-06-11 09:32
No problems found, it's OK. I just think ReplicaSchedulingPolicy should be consistent with the behavior of PropagationPolicy and OverridePolicy.

**Comment by RainbowMango** [comment] 2021-07-15 04:05
I think the issue has been resolved.
/close

**Closed by RainbowMango** 2021-07-15 04:05 UTC
Labels: kind/feature
