### ISSUE TITLE
The result of replace/remove the Registry in ImageOverrider is incorrect

### ISSUE THREAD

**Issue by ranzhouol** [karmada-io/karmada#2585] opened 2022-09-28 01:10 UTC
**What happened**:
First I distributed a deployment with ` image: ubuntu/nginx`, 
![image](https://user-images.githubusercontent.com/67987211/192487373-b1000c83-d403-4c1c-8d08-1cb32f319fb9.png)
  and then created an ImageOverrider to `remove the Registry`, i.e
```
apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  name: myapp-overridepolicy1
  namespace: test
spec:
  resourceSelectors:
    ...
  overrideRules:
    ...
      overriders:
        imageOverrider:
          - component: Registry
            operator: remove
```
   I expected to get `image: nginx`, but the result didn't change. It was still `image: ubuntu /nginx`.
  Similarly, I created an ImageOverrider to `replace the Registry`:
```
apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  name: myapp-overridepolicy2
  namespace: test
spec:
  resourceSelectors:
    ```
  overrideRules:
    ```
      overriders:
        imageOverrider:
          - component: Registry
            operator: replace
            value: bitnami
```
  and I expected to get `image: bitnami/nginx`, but the result was
![image](https://user-images.githubusercontent.com/67987211/192664674-db3d6d49-d08c-4dff-b59f-fe95db645bcf.png)

**What you expected to happen**:
I want to get the result I expect
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.2.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): v1.2.0
- Others:

**Comment by RainbowMango** [comment] 2022-09-28 02:46
For the first case, you are trying to `remove` the `registry`, but there is no `registry` in `ubuntu/nginx`, the implied registry is `https://hub.docker.com`.  The rule of how we recognize `registry/repository/tag` is [present at the API](https://github.com/karmada-io/karmada/blob/fc196abf894fb271a8d2e9aba4440fcfc48db199/pkg/apis/policy/v1alpha1/override_types.go#L121-L132).
```yaml
imageOverrider:
  - component: Registry
    operator: remove
```

> I expected to get image: nginx, but the result didn't change. It was still image: ubuntu /nginx.

We shouldn't expect that, in my opinion, it works as expected.
I wonder is there a real use case that wants to override `ubuntu/nginx` to `nginx`?

**Comment by RainbowMango** [comment] 2022-09-28 02:49
The second case is the same, since there is no `registry` in `ubuntu/nginx`, so the `replace` acts like `add`. That's expected behavior too.

**Comment by RainbowMango** [comment] 2022-09-28 02:51
Discussion is still ongoing, but for now, it seems not a bug for me.
/remove-kind bug
/kind question

**Comment by ranzhouol** [comment] 2022-09-28 05:45
I misunderstood, now I understand, thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "karmada-io/karmada"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月28日(星期三) 上午10:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [karmada-io/karmada] The result of replace/remove the Registry in ImageOverrider is incorrect (Issue #2585)





 
Discussion is still ongoing, but for now, it seems not a bug for me.
 /remove-kind bug
 /kind question

**Comment by RainbowMango** [comment] 2022-09-28 06:22
Thanks for your feedback. I'm going to close this issue and PR #2586 now.
/close

**Closed by RainbowMango** 2022-09-28 06:22 UTC
Labels: kind/question
